### ISSUE TITLE
npm依赖下载失败

### ISSUE THREAD

**Issue by echohye** [sakitam-gis/raster-process#1]
![image](https://github.com/sakitam-gis/raster-process/assets/81301702/fe28ab39-c933-4030-906d-ffdb61b71412)

你好，请问npm下载这个依赖需要什么环境吗，我尝试了这几个node版本都没下载成功

**Comment by sakitam-fdd** [comment]
怀疑是 gdal 的问题，我手头没有 windows，暂时不太好测试；有试过 linux 下有问题吗
![image](https://github.com/sakitam-gis/raster-process/assets/19517451/60456cf9-bb26-4b71-abb5-e2f7d45b9d4d)

**Comment by echohye** [comment]
应该是gdal，单独下也拉取不下来🥲🥲
![image](https://github.com/sakitam-gis/raster-process/assets/81301702/9b457d57-5b43-468d-aff6-c85be1f6339b)

**Comment by echohye** [comment]
![image](https://github.com/sakitam-gis/raster-process/assets/81301702/9ab72da9-e8a5-493f-a04a-eb0316b89951)

@sakitam-fdd 你好，请问[README文档](https://github.com/sakitam-gis/raster-process/blob/master/README.md)的示例是在什么环境下运行的，我在windows平台依赖import不了

**Comment by echohye** [comment]
@sakitam-fdd 你好，请问为什么grib2数据转png后是灰色图，而不是[colorize.html](https://blog.sakitam.com/wind-layer/playgrounds/mapbox-gl/colorize.html)这种彩色图，灰色图是可以正常使用[wind-layer](https://github.com/sakitam-fdd/wind-layer)来渲染到地图上的吗

[wind-surface.jpeg](https://blog.sakitam.com/wind-layer/data/tiles/2023111700/2023111703/1/0/0/wind-surface.jpeg)
![image](https://github.com/sakitam-gis/raster-process/assets/81301702/e769ecd2-88ff-453b-85e9-78b97a5f51f2)

**Comment by sakitam-fdd** [comment]
@echohye 
1. 灰度图是编码后的，为了减小体积，当然你也可以使用非灰度的 tiff，但是这个目前是不会直接渲色的，这个出的主要是数据，与渲染无关
2. 这个切出来的灰度图瓦片是可以直接使用 https://blog.sakitam.com/wind-layer/playgrounds/mapbox-gl/colorize.html 这个来渲染的

**Comment by echohye** [comment]
> @echohye
> 
> 1. 灰度图是编码后的，为了减小体积，当然你也可以使用非灰度的 tiff，但是这个目前是不会直接渲色的，这个出的主要是数据，与渲染无关
> 2. 这个切出来的灰度图瓦片是可以直接使用 https://blog.sakitam.com/wind-layer/playgrounds/mapbox-gl/colorize.html 这个来渲染的

![image](https://github.com/sakitam-gis/raster-process/assets/81301702/6e980a67-ddfe-4259-9181-9d8ca01b317a)
请问这种只有RG通道有值的瓦片图是用raster-process制作的吗，我怎么转换不到这种效果

**Comment by echohye** [comment]
@sakitam-fdd 
请问这种只有RG通道有值的瓦片图是用raster-process制作的吗，我怎么转换不到这种效果
![image](https://github.com/sakitam-gis/raster-process/assets/81301702/6e980a67-ddfe-4259-9181-9d8ca01b317a)

**Comment by sakitam-fdd** [comment]
预处理你的原始格点数据，单要素存放，风的一般是 UU 和 VV两个通道，最多能支持三个要素一个文件比如海浪的，浪高浪向和周期，因为需要理解 jpeg 只有三个通道

**Comment by echohye** [comment]
> 预处理你的原始格点数据，单要素存放，风的一般是 UU 和 VV两个通道，最多能支持三个要素一个文件比如海浪的，浪高浪向和周期，因为需要理解 jpeg 只有三个通道

@sakitam-fdd 请问这种方式的数据预处理方法可以参考吗，比如GFS风数据，它的uv值有小数和负数，怎么把它处理至0-255的GB通道值

**Comment by echohye** [comment]
请问这个node版本推荐使用多少，示例处理 GFS 格点数据导入affine失败
![image](https://github.com/user-attachments/assets/2d1d9ea5-7469-4113-8cdf-3cbe0a655a65)
